//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoHungKitchenWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public long MenuId { get; set; }
        public int KitchenId { get; set; }
        public string MenuTitle { get; set; }
        public int Category { get; set; }
        public string PurchasePrice { get; set; }
        public string SalePrice { get; set; }
        public string Discount { get; set; }
        public string Description { get; set; }
        public string MenuPhoto { get; set; }
    }
}
