//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoHungKitchenWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public long OrderId { get; set; }
        public int CustomerId { get; set; }
        public int KitchenId { get; set; }
        public int PackageId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string DeliveryTime { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string Address { get; set; }
        public string GoogleAddress { get; set; }
        public string TotalAmount { get; set; }
        public string Tax { get; set; }
        public string Discount { get; set; }
        public string PaidAmount { get; set; }
        public Nullable<int> IsSaturday { get; set; }
        public Nullable<int> IsSunday { get; set; }
    }
}
