//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoHungKitchenWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackageDetail
    {
        public int PackageDetId { get; set; }
        public int PackageId { get; set; }
        public string PackageDay { get; set; }
        public string MenuIds { get; set; }
        public Nullable<decimal> PackageRate { get; set; }
        public string PackagePhoto { get; set; }
        public Nullable<int> DefaultMenuId { get; set; }
    }
}
