//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoHungKitchenWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPackage
    {
        public int PackageID { get; set; }
        public int KitchenId { get; set; }
        public int Category { get; set; }
        public int Cuisine { get; set; }
        public int PlanType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> IsSaturday { get; set; }
        public Nullable<int> IsSunday { get; set; }
        public decimal ActualWeeklyRate { get; set; }
        public decimal ActualMonthlyRate { get; set; }
        public decimal WeeklyRate { get; set; }
        public decimal MonthlyRate { get; set; }
        public int Status { get; set; }
    }
}
