//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoHungKitchenWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRider
    {
        public int RiderId { get; set; }
        public string RiderName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public string BikeNumber { get; set; }
        public string BikeType { get; set; }
    }
}
